services:
  kafka-producer:
    build: .
    container_name: kafka_producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"  
      KAFKA_TOPIC: "weather_data_raw"
      CSV_PATH: "/data/weather_data.csv"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - data-engineering

networks:
  data-engineering:
    name: data-engineering
