services:
  kafka-consumer:
    build: .
    container_name: raw_kafka_consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: "weather_data_raw"
      KAFKA_GROUP_ID: "raw_kafka_consumer"
      RAW_DIR: "/raw"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./raw-zone:/raw
    networks:
      - data-engineering

networks:
  data-engineering:
    name: data-engineering
