services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: weather_data
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - data-engineering
  dashboard:
    build: .
    container_name: weather-data-dashboard
    environment:
      PG_DSN: "postgresql://test:test@postgres:5432/weather_data"
    ports:
      - "8501:8501"
    networks:
      - data-engineering

volumes:
  pg_data:

networks:
  data-engineering:
    external: true
